version: "3.8"
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    container_name: redis_cache_container
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
